name: MediaLinker Builder
on:
  workflow_dispatch:
#  push:
#    branches:
#      - main

jobs:
  Docker-build:
    runs-on: ubuntu-latest
    name: Build Docker Image
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set Up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: MediaLinker-ALl
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 -t ${{ secrets.DOCKER_USERNAME }}/medialinker:latest -f Dockerfile . --push
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

      - name: MediaLinker-Emby
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 -t ${{ secrets.DOCKER_USERNAME }}/medialinker:emby -f Dockerfile-emby . --push
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

      - name: MediaLinker-Plex
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 -t ${{ secrets.DOCKER_USERNAME }}/medialinker:plex -f Dockerfile-plex . --push
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}